### PR TITLE
adjusted serializable object properties count

### PR DESCRIPTION
**Pull request by philipshurpik**
@ebdrup We faced with problem that in debitoor app we need bigger count limit for properties. 
What do you think about this?   
Should we make it configurable?  
Or just increase default count value?
cc @bubenshchykov

### CODE REVIEW

**Comment by bubenshchykov** [comment]
just by looking at code - it's a magic number, i don't know how previous "100" was picked up

does it mean that we can have up to 1000 props in failed object? or in array? why not 100000 then? :)

**Comment by ebdrup** [comment]
It was picked so the test don't cause the process to crash. Express puts the http/app object on some errors that caysed a crash. 
Feel free to do a PR with green tests ;-)

**Comment by eagleeye** [comment]
@ebdrup this PR is green) We had a real case with real object of 300 entities. It was credit note with 10 invalid lines. Fork is used in debitoor app, so we are going just to increase this magic number to 1000 for now.

**Comment by ebdrup** [comment]
You have the rights to merge an deploy to npm AFAIR.

**Pull request merged**
